import Navpar from "./components/Navpar";
import { Almarai } from "next/font/google";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const almarai = Almarai({
  weight: ["400", "700", "800"],
  subsets: ["arabic"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         className={almarai.className}
      >
  <div className="max-w-7xl mx-auto px-4">
    <Navpar />
    {children}
    </div>
         
       
      </body>
    </html>
  );
}
